// src/content/flavor-thoughts.ts
// Dry, sad-funny register. Spoken to no one, on an endless plain.
export const THOUGHTS = [
  "Did I leave the airlock open.",
  "If a tree falls on an alien planet, it's still my fault somehow.",
  "The stars look the same here. Probably aren't.",
  "I should have called her back.",
  "Hungry. Always.",
  "The grass remembers being stepped on. I think.",
  "Forty paces north, then nothing. Same as always.",
  "I used to be afraid of the dark. Now it's just Tuesday.",
  "Somewhere, a kettle is boiling without me.",
  "My boots are older than some of these stars.",
  "Two suns and not one of them will answer a question.",
  "I keep finding bones. I keep not asking whose.",
  "There's a word for this in a language I never learned.",
  "If I stop walking, will the planet notice.",
  "The notes say other people were here. The notes lie comfortably.",
  "I named a rock today. I will not be doing that again.",
  "Whatever I find, someone else can't. That's the deal.",
  "My shadow has two heads now. Charming.",
  "I think the grass is taller where someone cried.",
  "No score. No winning. Just the next ridge. Fine. Fine.",
  "I dreamt of doorways. Woke up outdoors.",
  "Pretty sure I've walked past that exact nothing before.",
  "The wind out here doesn't carry anything. Not even sound.",
  "I'd trade a specimen for a chair.",
  "Somebody folded this note with real care. For me. For anyone.",
  "Home was a direction once.",
  "I count my steps and then I lie about the number.",
  "The horizon keeps its promises by never arriving.",
  "I miss being late for things.",
  "If this is exploring, I was robbed of the brochure.",
  "The chest was empty. So was I. We understood each other.",
  "There's comfort in being small under a big indifferent sky.",
  "I'll rest at the next ridge. I always say that.",
  "My footprints fill back in. The planet tidies up after me.",
  "Found glass that used to be sand that used to be a beach somewhere.",
  "I talk to the grass now. It's a good listener. Low bar.",
  "The dark is just the light, resting.",
  "One day I'll find the edge. One day.",
  "I keep walking like the answer is geographic.",
  "Whoever I was: you'd be amazed how far the legs still go.",
];
